### ISSUE TITLE
Ajustar imagens do rodapé

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/e-blueinfo-wp-plugin#101]
- Exibir primeiro o logo dos apoiadores proporcional ao tamanho do logo da BIREME
- Em seguida exibir logo da BIREME centralizado

**Comment by renatomurasaki** [comment]
@marcioalvessilva ficou excelente! Acho que a bolinha com a bandeira ficou redundante, considerando que a informação do país está bem explícita nos logos. Vamos apostar que os demais países seguirão o mesmo estilo de identidade visual clara do país de origem, Muito obrigado.
