### ISSUE TITLE
Alterar o logo do Ministério da Saúde do Perú na peça de comunicação de lançamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#102]
O logo correto é o que foi usado nas outras peças

![image](https://user-images.githubusercontent.com/1226218/100769002-43e68500-33da-11eb-8a5d-9bd997bc5260.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva trocar o logo na seguinte peça em português e espanhol

![divulgacao-lancamento-PT](https://user-images.githubusercontent.com/1226218/110006333-449ff780-7cf8-11eb-83c9-9e2a4be5c28c.jpg)

**Comment by marcioalvessilva** [comment]
@renatomurasaki !
Com o logo do peru modificado não temos espaço para deixar tudo em uma única linha.
Lembro de você me informar que o logo da BIREME deve ter o mesmo tamanho para esse projeto

![image](https://user-images.githubusercontent.com/48724136/110325136-be382e00-7ff5-11eb-8022-e95df76fb974.png)

Se eu puder separar eu faria assim e acho que ainda consigo melhorar um pouco a qualidade dos logos que estão pequenos

![image](https://user-images.githubusercontent.com/48724136/110326060-e96f4d00-7ff6-11eb-8639-13b481ae2cfb.png)

**Comment by marcioalvessilva** [comment]
Pensando em uma melhor exibição no twitter fiz essa versão, assim teremos uma versão para o facebook e outra para o twitter

![image](https://user-images.githubusercontent.com/48724136/110328787-8a133c00-7ffa-11eb-80c6-25d40b1670bc.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva Acho que está ok colocar o logo da OPAS ao lado do link. Falando em link, repare que está faltando o hífen: e-blueinfo.bvsalud.org

**Comment by marcioalvessilva** [comment]
Versão PT

![lancamento](https://user-images.githubusercontent.com/48724136/111310354-bef74280-863b-11eb-9fd0-f1d80275af3c.jpg)

Versão ES
![lanzamiento](https://user-images.githubusercontent.com/48724136/111310357-c0286f80-863b-11eb-8673-7a8d92af8faa.jpg)
