### ISSUE TITLE
Editar o banner do rodapé do Perú, retirando o logo "El Perú Primero"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#107]
Banner atual
![image](https://user-images.githubusercontent.com/1226218/108221139-38bc0f00-7116-11eb-9b63-19863ff3e326.png)

Retirar o logo "El Perú Primero" e ajustar a posição dos dois primeiros logos.

**Comment by marcioalvessilva** [comment]
Boa tarde!
Foi removido das paginas e do app.

Foi encontrado outra imagem com o logo, posso editar e remover?

ex:
![image](https://user-images.githubusercontent.com/48724136/108232744-d49f4800-7121-11eb-9c75-abaa07fa7730.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva sim, pode retirar. Obrigado pela observação!

**Comment by marcioalvessilva** [comment]
Já tínhamos deixo pronto o @wilsonmoura  já deixou atualizado
![image](https://user-images.githubusercontent.com/48724136/110142618-1e8c5d00-7db5-11eb-8428-c415a57c3b88.png)

**Comment by renatomurasaki** [comment]
OK! Nas próximas, ao ver finalizada a tarefa, pode fechar o issue @marcioalvessilva . Obrigado!
