### ISSUE TITLE
Mostrar a coleção Guias OPAS/OMS como card na seção Outros Conteúdos de todos os países

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#109]
Mostrar antes do card "Buscar evidências científicas na Biblioteca Virtual em Saúde"

**Comment by renatomurasaki** [comment]
@wilsonmoura por favor, mostrar primeiro o card das Guias OPAS/OMS e depois Buscar Evidencia

**Comment by wilsonmoura** [comment]
@renatomurasaki ajustes realizados. Favor validar.

**Comment by renatomurasaki** [comment]
@wilsonmoura obrigado!
