### ISSUE TITLE
Propor arte para destacar no site de divulgação (https://e-blueinfo.bvsalud.org/) que o e-BlueInfo conta com nova versão

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#112]

**Comment by marcioalvessilva** [comment]
@renatomurasaki 
Segue proposta de banner fixo para inserir no site e-BlueInfo informando a que existe uma nova versão do app

![image](https://user-images.githubusercontent.com/48724136/110358302-0158c800-801b-11eb-8f72-0b0949d8e62d.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva qual a sugestão para colocar esse banner no site do e-BlueInfo?

**Comment by marcioalvessilva** [comment]
Eu fiz uma sessão que depois posso remover!

![image](https://user-images.githubusercontent.com/48724136/110366186-b643b280-8024-11eb-890f-dd3dd0d2782f.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva o que acha de mudar o texto para "Conheça a nova versão do e-Blueinfo" e retirar o texto e ícones de disponível nas lojas (...)? Quero evitar de dar a sensação para aqueles que já usam que há a necessidade de fazer novo download. Também acho que poderíamos criar uma página para explicar as novas funcionalidades, que seria acessada clicando nesse banner. Essa página pode ser um mosaico com os textos explicativos de todas as artes que publicaremos nas redes sociais sobre as novas funcionalidades. Que tal?

**Comment by marcioalvessilva** [comment]
bom dia @renatomurasaki 
Por favor validar 
https://e-blueinfo.teste.bvsalud.org/
https://e-blueinfo.teste.bvsalud.org/novidades/

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. Faltou atualizar o texto: "Conheça a nova versão do e-Blueinfo".
A página com o mosaico não seria exatamente com as imagens das redes sociais, mas sim com os textos explicativos. Poderia ter um print da tela correspondente e ao lado o texto explicativo, por exemplo.

**Comment by renatomurasaki** [comment]
Exemplo, baseado no site https://mailchimp.com/pt-br/

![image](https://user-images.githubusercontent.com/1226218/110798514-030fcf00-8259-11eb-9f70-9b13a9f3d700.png)

**Comment by marcioalvessilva** [comment]
Entendi @renatomurasaki , vou avançar neste sentido
Me confirma os textos para os três idiomas do banner e o nome das páginas, já vou deixar criado.

**Comment by marcioalvessilva** [comment]
Atualizado, por favor verificar!
https://e-blueinfo.teste.bvsalud.org/
https://e-blueinfo.teste.bvsalud.org/novidades/

**Comment by renatomurasaki** [comment]
### Traduções do banner
**Espanhol**
Conozca la nueva versión de e-BlueInfo

**Inglês**
Get to know e-BlueInfo new version

### Título da página
**Português**
Novas funcionalidades do e-BlueInfo

**Espanhol**
Nuevas funcionalidades de e-BlueInfo

**Inglês**
e-BlueInfo new features

@marcioalvessilva já pode utilizar os textos que criei nos 3 idiomas nos issues #129 #131 #132

**Comment by marcioalvessilva** [comment]
Páginas atualizadas!
Vou aguardas as modificações que o Wilson deve fazer para alterar as imagens

**Comment by renatomurasaki** [comment]
@marcioalvessilva já atualizei os issues com a tradução para o inglês
