### ISSUE TITLE
Alterar o destaque "Dados dos países participantes" presente na página inicial do site de divulgação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#113]
### Atual
![image](https://user-images.githubusercontent.com/1226218/110009256-85e5d680-7cfb-11eb-94d6-7b86c14f0ab6.png)

### Proposta de mudança
Retirar as bandeiras, para que a manutenção do site fique mais sustentável, e alterar o texto para:

**Estatísticas de acesso**
Clique aqui e confira os dados de acesso ao e-BlueInfo.

**Comment by marcioalvessilva** [comment]
Bom dia @renatomurasaki 
Pensei em modificar esse destaque 
![image](https://user-images.githubusercontent.com/48724136/110318841-c8096380-7fec-11eb-9dd0-f6437444dd45.png)

Posso atualizar na instância de teste?

**Comment by renatomurasaki** [comment]
@marcioalvessilva gostei das imagens! Mais representativas. Observe que sugeri mudança no texto do primeiro destaque.

**Comment by renatomurasaki** [comment]
@marcioalvessilva veja também o issue #114 que tem relação à proposta que você fez.
