### ISSUE TITLE
Aumentar tamanho da letra de alguns textos da página inicial do site de divulgação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#115]
Aumentar o tamanho das letras dos textos marcados em vermelho na imagem abaixo

![image](https://user-images.githubusercontent.com/1226218/110011519-4ec4f480-7cfe-11eb-8a06-88ca1fa1330e.png)

**Comment by marcioalvessilva** [comment]
Tamanho padrão dos textos alterados

- home
![image](https://user-images.githubusercontent.com/48724136/110121096-b467be00-7d9c-11eb-8fb0-f350408dcbd2.png)


- páginas internas
![image](https://user-images.githubusercontent.com/48724136/110121398-16c0be80-7d9d-11eb-81f2-4b3e3d22f992.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva não senti diferença. Mas percebi um efeito colateral no menu da página interna, que o quebrou em duas linhas
![image](https://user-images.githubusercontent.com/1226218/110123732-09f19a00-7da0-11eb-996e-179891d7650d.png)

**Comment by marcioalvessilva** [comment]
@renatomurasaki 
- Tamanho original 16px, primeira modificação 18px e agora 19px
![image](https://user-images.githubusercontent.com/48724136/110132766-49bd7f00-7daa-11eb-8404-803dc70a61ef.png)

- Menu alterado, permitindo crescimento
![image](https://user-images.githubusercontent.com/48724136/110132822-580b9b00-7daa-11eb-8e6b-426ab443d561.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva não sei era cache, mas ao carregar a página notei a diferença.

Obrigado!
