### ISSUE TITLE
Ajustes no texto da página https://e-blueinfo.teste.bvsalud.org/informacoes-dos-paises/

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#116]
**DE** - Informações dos Países
**PARA** - Sobre os conteúdos dos países

**DE** - Selecione abaixo o país desejado para ter mais informações.
**PARA** - Selecione abaixo o país desejado e conheça como a informação disponíveis no e-BlueInfo é organizada e atualizada.

Aumenta o tamanho da fonte do texto "Selecione abaixo ..."

**Comment by marcioalvessilva** [comment]
Bom dia!
Como vai ficar as versões em Espanhol e Inglês
EN: Country Information 
- Select the desired country below for more information.

ES: Información del país
Seleccione el país deseado a continuación para obtener más información.

**Comment by renatomurasaki** [comment]
### Traduções
**Espanhol**
Sobre los contenidos de los países
Seleccione abajo el pais deseado y conozca como la información disponible en e-BlueInfo es organizada y actualizada

**Inglês**
About the contents of the countries
Select the desired country below and find out how the information available on e-BlueInfo is organized and updated.

**Comment by marcioalvessilva** [comment]
@renatomurasaki , Boa tarde!
Textos atualizados
PT - https://e-blueinfo.teste.bvsalud.org/informacoes-dos-paises/
EN - https://e-blueinfo.teste.bvsalud.org/en/country-information/
ES - https://e-blueinfo.teste.bvsalud.org/es/informacion-del-pais/

**Comment by renatomurasaki** [comment]
Obrigado!
