### ISSUE TITLE
Ajustes no texto da página do Brasil

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#117]
**DE** - Breve Introdução
**PARA** - eliminar este título

**DE** - Informação sobre as Comunidades
**PARA** - Sobre os conteúdos disponíveis

**DE** - O app e-BlueInfo conta com uma comunidade que reúne materiais afetos à APS (...)
**PARA** - O app e-BlueInfo conta com conteúdos que reúnem materiais afetos à APS (...)

**DE** - Informação sobre as Categorias
**PARA** - Sobre as coleções de documentos

**DE** - O app conta atualmente com 6 Categorias:
**PARA** - O app conta atualmente com 6 coleções de documentos:

Eliminar as seções que não tem conteúdo

Estatística
Vídeos
Depoimentos
Parceiros

A seção Rede Social mostrará os posts que iremos marcar com hastag

Incluir no final, antes do rodapé da BIREME, o mesmo rodapé do Brasil utilizado dentro do App.

**Comment by marcioalvessilva** [comment]
Texto atualizado e sessões ocultas sempre que não houver conteúdo.
Estou buscando solução css separar sessões entre impares e pares

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. Falta incluir no final, antes do rodapé da BIREME, o mesmo rodapé do Brasil utilizado dentro do App.

**Comment by renatomurasaki** [comment]
@marcioalvessilva esqueci de ajustar o seguinte texto:
**DE** - Informação sobre o Comitê Local de Conteúdos
**PARA** - Sobre o Comitê Local de Conteúdos

**Comment by marcioalvessilva** [comment]
Texto atualizado e logos inseridos

**Comment by renatomurasaki** [comment]
@marcioalvessilva pode retirar o título da seção "Parceiros", por favor

**Comment by marcioalvessilva** [comment]
Olá @renatomurasaki, título removido

**Comment by renatomurasaki** [comment]
Obrigado!
