### ISSUE TITLE
Ajustes no texto da página do Perú

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#119]
**DE** - Información sobre las Comunidades
**PARA** - Sobre los contenidos disponibles

**DE** - O app e-BlueInfo conta com uma comunidade que reúne materiais afetos à APS (...)
**PARA** - O app e-BlueInfo conta com conteúdos que reúnem materiais afetos à APS (...)

**DE** - Información sobre las Categorias
**PARA** - Sobre las colecciones de documentos

**DE** - Información sobre el Comité Local de Contenidos
**PARA** - Sobre el Comité Local de Contenidos

**Outras ações:**

- Inverter a ordem dos logos. Primeiro mostra Perú Ministerio de Salud.
- Aplicar o mesmo estilo no título das seções que foi usado na página do Brasil

**Comment by marcioalvessilva** [comment]
@renatomurasaki 
Texto atualizado e posição das imagens alteradas

ES - https://e-blueinfo.teste.bvsalud.org/es/peru/
PT - https://e-blueinfo.teste.bvsalud.org/peru-pt/ 
EN - https://e-blueinfo.teste.bvsalud.org/en/peru-en/

Obs: não localizei esse texto 
DE - O app e-BlueInfo conta com uma comunidade que reúne materiais afetos à APS (...)
PARA - O app e-BlueInfo conta com conteúdos que reúnem materiais afetos à APS (...)

**Comment by renatomurasaki** [comment]
Está ok, obrigado. Estes textos não localizados é porque são texto da página do Brasil. Erro de copy&paste.
