### ISSUE TITLE
Alteração na tradução do menu

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#123]
### Tradução para o Espanhol:
**DE:** Início
**PARA:** Inicio

**DE:** Datos
**PARA:** Estadísticas

### Tradução para o Português
**DE:** Dados
**PARA:** Estatísticas

### Tradução para o Inglês
**DE:** Data
**PARA:** Statistics

**Comment by marcioalvessilva** [comment]
Menu atualizado!
