### ISSUE TITLE
Alterar título da página da Busca por Evidencias (BVS Infobutton - app/infobutton)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#124]
### Português
**DE:** Pesquisa Contextualizada
**PARA:** Buscar evidências científicas na Biblioteca Virtual em Saúde

### Espanhol
**DE:** Búsqueda Contextualizada
**PARA:** Buscar evidencia científica en la Biblioteca Virtual en Salud

### Inglês
**DE:** Contextualized Search
**PARA:** Search for scientific evidence in the Virtual Health Library

**Comment by wilsonmoura** [comment]
Realizado em 6b7a842f4a76e1e67d5d3059370096a7c920ae3e
