### ISSUE TITLE
Alterar o texto automático que aparece ao selecionar o sistema de código "DeCS/MeSH"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#125]
![image](https://user-images.githubusercontent.com/1226218/110370606-aa5aef00-802a-11eb-93a7-1cd38e4aac56.png)
**DE:** Código DeCS/MeSH
**PARA:** Termo ou código DeCS/MeSH

Testei com os dois, usando o texto e o código, e funcionam

**Comment by wilsonmoura** [comment]
Ajuste realizado.
