### ISSUE TITLE
Corrigir erro de layout e escolha do sistema de código após voltar para o formulário do BVS Infobutton depois de realizar uma busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#126]
![image](https://user-images.githubusercontent.com/1226218/110371379-a8456000-802b-11eb-8ba0-265091c11d56.png)

Problemas:

- O código ou o texto colocado na busca fica sobreposto ao título do campo.
- O sistema de código não se mantem com a escolha do usuário. No exemplo era para ter aparecido DeCS/MeSH e foi para a opção padão ICD-10

**Comment by wilsonmoura** [comment]
Ajuste realizado.
