### ISSUE TITLE
Material de divulgação: Documentos favoritos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#131]
A estrutura deste material deve seguir a mesma criada para a busca de evidências na BVS

### Título
**Português**
Documentos favoritos

**Espanhol**
Documentos favoritos

**Inglês**
Favorite documents

### Texto principal
**Português**
Na nova versão do e-BlueInfo você pode armazenar seus documentos favoritos e acessá-los facilmente a qualquer momento. Para usar esta facilidade, crie um usuário e senha para se autenticar ou utilize a sua conta do Facebook ou Google.

**Espanhol**
En la nueva versión de e-BlueInfo usted puede almacenar sus documentos favoritos y accederlos fácilmente en cualquier momento. Para usar esta facilidad, cree un usuario y contraseña para autenticarse o utilice su cuenta de Facebook o Google.

**Inglês**
In the new version of e-BlueInfo you can store your favorite documents and access them easily at any time. To use this feature, create a username and password to authenticate yourself or use your Facebook or Google account.

**Comment by renatomurasaki** [comment]
@marcioalvessilva favor retirar a palavra facilmente, fácilmente e easily dos textos, respectivamente em português, espanhol e inglês.

**Comment by renatomurasaki** [comment]
@marcioalvessilva retirar tanto do material de divulgação como da página de novidades do site do e-BlueInfo, por favor.

**Comment by marcioalvessilva** [comment]
@renatomurasaki páginas atualizadas e posts enviado por email
