### ISSUE TITLE
Criar página da Guatemala

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#133]
**Iniciar a página com o texto abaixo**
El objetivo de e-BlueInfo es reducir la inequidad de acceso y uso de la normativa legal, regulatoria y evidencia científica. En Guatemala esta aplicación móvil fue lanzada oficialmente en noviembre de 2019. 

Los contenidos de e-BlueInfo son documentos oficiales y vigentes generados por: Hospitales, Direcciones de Regulación, Programas, Unidades, Departamentos y Secciones del Ministerio de Salud Pública y Asistencia Social, para facilitar la autoformación del personal de salud en Guatemala, poniendo a disposición documentos digitales relacionados a la promoción, prevención, atención y rehabilitación.

La selección y ordenamiento de las colecciones se basa en la estrategia de atención primaria en salud que requiere de procesos de gestión y atención integrales con recurso humano formado para garantizar la salud como un derecho humano.

**Sobre los contenidos disponibles**
Guatemala tiene 21,294 comunidades, de cuatro pueblos: Maya, Garifuna, Xinca y Meztizo/ladino.   A las cuales a través de e-BlueInfo en un marco de las colecciones “Atención Primaria en Salud”, y la nueva: “Covid-19”,  se espera fortalecer a los profesionales de salud a nivel público, privado y académico, con las herramientas que contribuyan al acceso y cobertura universal de la salud impactando en el desarrollo de la población.

**Sobre las colecciones de documentos**
Con la finalidad de crear innovación tecnológica en Guatemala para la atención integral, e-BlueInfo tiene un enfoque de proveer herramientas útiles al personal de salud. 

En e-blueInfo encuentra documentos oficiales y vigentes, que contribuyen a garantizar la salud familiar, individual y comunitaria. Guatemala tiene dos grandes colecciones de documentos que serán actualizados constantemente:

1.- **Atención Primaria en Salud**: Atención Integral e Integrada (ALL) , Género y Pertinencia Cultural en Salud (GP), Marco Legal y Jurídico en Salud (ML), Promoción, Educación e Investigación en Salud (PEIS), Vigilancia de la Salud y Mejora Continua (VS).

2.- **Covid-19**: Marco Legal y Jurídico del COVID19 (MLC), Formularios y Registros COVID-19 (FOREC), Protocolos y lineamientos para el COVID-19 (PLC), Guías Educativas sobre atención Covid-19 (GEC), Manejo Clínico de COVID-19 (MCC).

El Ministerio de Salud Pública y Asistencia Social quiere una mejora tecnológica en Guatemala, es por eso por lo que busca nuevas tendencias de comunicación para el futuro y así facilitar sus funciones enfocadas en el fortalecimiento de la salud en Guatemala.

**Sobre el Comité Local de Contenidos**
En el año 2019, se realizó una convocatoria por parte de OPS/OMS Guatemala para conformar un equipo de trabajo y comité de selección de documentos, en el cual se conformó en esa primera instancia por el equipo de la Biblioteca Virtual en Salud de Guatemala, Ministerio de Salud Pública y Asistencia Social a través de la Dirección General de Sistema Integral de Atención en Salud y el apoyo técnico a través de la OPS/OMS Guatemala.

Se coordino el trabajo de equipo para la creación de la colección de APS de e-Blueinfo para Guatemala, se identificó y seleccionó los documentos para la atención primaria de salud y la BVS fue quien dio el apoyo técnico para la organización de las carpetas con BIREME, así como la capacitación para el registro de los documentos.

Se logró coordinar con el Viceministerio de Atención Primaria el lanzamiento de este aplicativo el 27 de noviembre de 2019, en el auditórium mayor del INCAP; con participación de Representantes del Ministerio, Decanos de las facultades de ciencias médicas de las Universidades del País, representantes del INCAP, Direcciones de áreas Departamentales, género y pertinencia cultural, atención integral e integrada, vigilancia de la salud y mejora continua, se contó con la participación del Director de BIREME el Dr. Diego González a través de un video, así como el representante de la OPS/OMS Guatemala el Dr. Oscar Barreneche y la Asesora de Sistemas de Servicios de Salud la Dra. Caroline Chang.

Para el lanzamiento de la versión 2.0 el Viceministerio de Atención Primaria ha designado un equipo conformado por: miembros del Sistema Integral de Atención en Salud (SIAS), del Departamento de Regulación de los Programas de Atención a las Personas (DRPAP), del Viceministerio Técnico y del Viceministerio de Hospitales.

El Equipo de Ministerio de Salud y las bibliotecas del Instituto de Nutrición de Centroamérica y Panamá; y la BVS conforman: “El comité de contenidos local de e-BlueInfo”. La bibliotecóloga de la BVS, experta que es quien se encarga de revisar y crear las síntesis de los contenidos que tiene cada documento para que los usuarios cuando ingresen puedan encontrar información descriptiva del tipo de documento que se encuentra dentro de la app y página Web.

**Comment by marcioalvessilva** [comment]
Conteúdo cadastrado

ES - https://e-blueinfo.teste.bvsalud.org/es/guatemala/
PT - https://e-blueinfo.teste.bvsalud.org/guatemala-pt/
EN - https://e-blueinfo.teste.bvsalud.org/en/guatemala-en/
