### ISSUE TITLE
Eliminar barra de acessibilidade, idiomas e menu das páginas que estão no site de divulgação e que são abertas no App

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#135]
Esses elementos devem ser eliminados somente na visualização dentro do App e-BlueInfo. Quando acessadas via site de divulgação, estes elementos continuam sendo mostrados normalmente.

Em negrito as páginas que precisam sofrer esta mudança:

Login
País
  |__ **Saiba mais**
  |__ Escolher país
Conteúdos
Sobre
  |__ **Por que e-BlueInfo**
  |__ **Apoiadores**
Ajuda
  |__ Contato
  |__ **Tutorial**
Idioma

**Comment by renatomurasaki** [comment]
@wilsonmoura é necessário algum ajuste nas páginas ou o App tem utilizado páginas paralelas àquelas mostradas no site do e-BlueInfo?

**Comment by renatomurasaki** [comment]
@wilsonmoura também ocultar a barra para baixar o aplicativo, presente agora no rodapé

**Comment by wilsonmoura** [comment]
Realizado em bireme/wordpress-themes#45
