### ISSUE TITLE
Alteração imediata na página de apoiadores institucionais

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#136]
Incluir El Salvador no texto.

**Comment by renatomurasaki** [comment]
@marcioalvessilva vejo a alteração via web na nova página que será utilizada na versão 2 - https://e-blueinfo.bvsalud.org/apoiadores-institucionais/ 

Mas na página atual, usada pelo App, ainda não. Poderia verificar, por favor?

**Comment by marcioalvessilva** [comment]
@renatomurasaki para mim aparece alterado, pode me enviar um print.

**Comment by renatomurasaki** [comment]
Márcio, estou olhando no APP. Seguem os prints:

![Screenshot_20210311-100946](https://user-images.githubusercontent.com/1226218/110793523-79a9ce00-8253-11eb-90b4-76bb407beecf.png)
![Screenshot_20210311-101001](https://user-images.githubusercontent.com/1226218/110793528-7adafb00-8253-11eb-93fc-ebe88aca7a78.png)
![Screenshot_20210311-100916](https://user-images.githubusercontent.com/1226218/110793531-7b739180-8253-11eb-9c59-148687c34569.png)

**Comment by marcioalvessilva** [comment]
@renatomurasaki, textos atualizados!
Me conforme se precisa alterar a ordem dos países, eu apenas inserir El Salvador depois do brasil e mantive a ordem que estava.

**Comment by renatomurasaki** [comment]
@marcioalvessilva está correto. A ordem é sempre a alfabética, como você fez. Obrigado!
