### ISSUE TITLE
Publicar video de testemunho de El Salvador, na seção da página do pais "Testemunhos"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#139]
Vídeo enviado por e-mail com subject "Video de e-BlueInfo El Salvador"

**Comment by marcioalvessilva** [comment]
@renatomurasaki, 
Video inserido.
obs: Em primeiro momento esta área foi pensada apenas para textos, então a melhor divisão foi de 3 colunas por linha, caso ache que o video ficou pequeno posso divider em duas colunas. mas o video tem o botão de ampliar.

**Comment by renatomurasaki** [comment]
@marcioalvessilva pode realizar a mudança que você sugeriu de 2 colunas a fim de ampliar a área do thumbnail. Pode carregar no youtube, no modo privado, apenas visualizável para quem tem o link.

**Comment by marcioalvessilva** [comment]
Página configurada!
