### ISSUE TITLE
Incluir banner para a comunidade COVID-19 e imagem de rodapé para El Salvador

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#140]
**Formato PNG**
![Banner-COVID 19 El Salvador](https://user-images.githubusercontent.com/1226218/111197269-0a0e4880-859d-11eb-9e13-18096cf21cab.png)
![logo](https://user-images.githubusercontent.com/1226218/111197275-0b3f7580-859d-11eb-941d-d529d25903c5.png)

**Formato JPG**
![Banner-covid-19 El-Salvador](https://user-images.githubusercontent.com/1226218/111197301-15fa0a80-859d-11eb-8739-11643a4259a4.jpg)
![logo](https://user-images.githubusercontent.com/1226218/111197304-1692a100-859d-11eb-96f4-0a2a5803e3e0.jpg)

**Comment by wilsonmoura** [comment]
@renatomurasaki banner e imagem do rodapé aplicados conforme solicitado.
