### ISSUE TITLE
Propor banner para a comunidade Guias OPAS/OMS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#142]
Repare nas coleções desta comunidade

https://sites.teste.bvsalud.org/e-blueinfo/pt/app/collection/?community=60

Como ponto de partida, os documentos destas coleções vem da base https://sites.bvsalud.org/bigg/en/biblio/

**Comment by marcioalvessilva** [comment]
@renatomurasaki 
Eu criei esse card para a comunidade OPAS/OMS, acredito que possa ser usado como banner

![card](https://user-images.githubusercontent.com/48724136/111241889-c9ceba80-85dc-11eb-8048-986250f0ba60.jpg)

**Comment by renatomurasaki** [comment]
@marcioalvessilva guarde essa arte, caso façamos a substituição do card atual. Como falamos, o banner precisa reflitir o contexto das coleções de documentos.

**Comment by marcioalvessilva** [comment]
Segue nova arte
![card-ops](https://user-images.githubusercontent.com/48724136/111384915-d1e43400-8688-11eb-88b3-d7e2272da2ad.jpg)

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. Fico no aguardo dos ajustes que conversamos sobre o profissional de saúde.

**Comment by marcioalvessilva** [comment]
@renatomurasaki, segue nova imagem
![card-ops](https://user-images.githubusercontent.com/48724136/111504495-7a94a100-8726-11eb-8568-5bbbd276c6ef.jpg)

**Comment by renatomurasaki** [comment]
@marcioalvessilva @wilsonmoura banner aprovado para a comunidade Guias OPAS/OMS

**Comment by renatomurasaki** [comment]
@wilsonmoura favor aplicar para encerrar o issue

**Comment by wilsonmoura** [comment]
@renatomurasaki banner aplicado conforme solicitado.
