### ISSUE TITLE
Criar a seção "Sobre os conteúdos da OPAS/OMS" na página https://e-blueinfo.teste.bvsalud.org/informacoes-dos-paises/

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#143]
**Português**
Sobre os conteúdos da OPAS/OMS

**Espanhol**
Sobre los contenidos de OPS/OMS

**Inglês**
About PAHO/WHO contents

**Comment by marcioalvessilva** [comment]
@renatomurasaki 
Foi criado mais um card com link para página OPAS/OMS
Aguardo conteúdo

**Comment by renatomurasaki** [comment]
@marcioalvessilva creio que seja melhor deixar o texto "Sobre os conteúdos da OPAS/OMS" com a mesma formatação do texto "Sobre os conteúdos dos países"

**Comment by marcioalvessilva** [comment]
Legal vou alterar o template da página

**Comment by renatomurasaki** [comment]
@marcioalvessilva falta alterar o estilo do texto "Sobre os conteúdos da OPAS/OMS" para que fique com a mesma formatação do texto "Sobre os conteúdos dos países"

**Comment by marcioalvessilva** [comment]
Página atualizada!
