### ISSUE TITLE
Alterar textos da página https://e-blueinfo.teste.bvsalud.org/novidades/

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#144]
Retirar o texto "Na nova versão do e-BlueInfo você também pode" e "Na nova versão do e-BlueInfo você pode" que é mostrado na versão português e nos demais idiomas, deixando os texto menos repetitivos e iniciando diretamente com:

- Busque evidências (...)
- Armazene seus documentos favoritos para acessá-los (...)
- Liste todos os documentos já visitados para acessá-los rapidamente (...)

**Versão espanhol**:
- Busque evidencias (...)
- Almacene sus documentos favoritos para accederlos (...)
- Liste todos los documentos ya visitados para accederlos rápidamente (...)

**Versão inglês**:
- Search for scientific (...)
- Store your favorite documents (...)
- List all the documents (...)

**Comment by marcioalvessilva** [comment]
Conteúdo atualizado, por favor validar!

PT -https://e-blueinfo.teste.bvsalud.org/novidades/
ES - https://e-blueinfo.teste.bvsalud.org/es/nuevas-funcionalidades-de-e-blueinfo/
EN - https://e-blueinfo.teste.bvsalud.org/en/e-blueinfo-new-features/
