### ISSUE TITLE
Mesmo traduzidos, o nome, a descrição e a imagem do card da Comunidade "Guias OPAS/OMS" só aparecem em português no ambiente de testes

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#145]
De acordo com a @suelisuga a tradução foi feita, como se vê abaixo

![image](https://user-images.githubusercontent.com/1226218/111318463-d9351e80-8643-11eb-9cdd-5c96bbb6c1ca.png)

Entretanto, as traduções não aparecem na interface de testes, como se nota abaixo:

**Espanhol**
![image](https://user-images.githubusercontent.com/1226218/111318898-3cbf4c00-8644-11eb-8b24-15f64fd6e9d2.png)

**Inglês**
![image](https://user-images.githubusercontent.com/1226218/111318814-2913e580-8644-11eb-9530-0a4f0d4c0bb9.png)

**Comment by viniciusandrade** [comment]
Realizei análise inicial e verifiquei que a API do FI-ADMIN para o nível comunidade não esta realizando corretamente o tratamento para o parâmetro de idioma. Criado issue para ajuste.

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste realizado na API do FI-ADMIN, quando possível favor validar.

Obrigado.

**Comment by renatomurasaki** [comment]
Aparentemente ok! Entretanto, o @wilsonmoura me disse que vai conversar contigo pois parece que precisa de ajuste

**Comment by renatomurasaki** [comment]
@viniciusandrade efeito colateral na imagem do card. Está aparecendo outra imagem. O @wilsonmoura falará contigo sobre isso.

**Comment by wilsonmoura** [comment]
@viniciusandrade no FI-ADMIN, o usuário que pode cadastrar uma imagem diferente de comunidade pra cada idioma. E parece que não tá incluindo o link correto da imagem em alguns idiomas. Veja exemplo testado na comunidade Guias OPAS/OMS:

PT - /uploads/collection/image/logoopas_site_330x220.png
ES - http://docs.bvsalud.org/collection/image/blueverticalspanish.png
EN - http://docs.bvsalud.org/collection/image/who-paho.png

Percebi também que algumas das imagens não estão com a resolução ideal. O padrão correto de resolução para essas imagens das comunidades é de 600x350.

**Comment by viniciusandrade** [comment]
@wilsonmoura revisei o código da API para montar corretamente a URL da imagem nos 3 idiomas. 

Subi as novas imagens enviadas pelo @marcioalvessilva.

Favor verificar se agora esta tudo OK.

Obrigado.

**Comment by wilsonmoura** [comment]
@viniciusandrade agora está tudo OK. Obrigado.

**Comment by viniciusandrade** [comment]
@renatomurasaki ajustes realizados e validados pelo @wilsonmoura.
