### ISSUE TITLE
Mudar o texto inicial do site de divulgação do e-BlueInfo, considerando o ingresso das coleções de Guias da OPAS/OMS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#146]
Na página inicial, alterar o texto seguinte texto nos diferente idiomas:

### Português
**DE:** e-BlueInfo é um aplicativo para os profissionais de saúde do Brasil e Peru totalmente gratuito!
**PARA:**  e-BlueInfo é um aplicativo para profissionais de saúde totalmente gratuito, com informação do Brasil, El Salvador, Guatemala, Peru e OPAS/OMS.

### Espanhol
**DE:** e-BlueInfo es un aplicativo para profesionales de la salud de Brasil y Perú totalmente gratis!
**PARA:** e-BlueInfo es un aplicativo para profesionales de la salud totalmente gratis, con información de Brasil, El Salvador, Guatemala, Perú y OPS/OMS!

### Inglês
**DE:** e-BlueInfo is a free app for healthcare professionals from Brazil and Peru!
**PARA:** e-BlueInfo is a free app for healthcare professionals with information from Brazil, El Salvador, Guatemala, Peru and PAHO/WHO!

**Comment by marcioalvessilva** [comment]
Textos atualizados!
obs: no texto em pt é o único que termina com ponto final e coloquei com exclamação.
Qualquer coisa me avise

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado! Poderia acomodar o texto mais na horizontal, para diminuir a altura desta seção? Acho que ainda há um espaço nas laterais que pode ser aproveitado.

**Comment by marcioalvessilva** [comment]
Ajustes Realizados!
Área de conteúdo mais horizontal e altura diminuída.
