### ISSUE TITLE
Alterar menu "Sobre os conteúdos dos países"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#147]
Tendo em vista a inclusão das guias OPAS/OMS, precisamos alterar o nome desta opção no Menu:

**Português**
Sobre os conteúdos

**Espanhol**
Sobre los contenidos

**Inglês**
About the contents

**Comment by marcioalvessilva** [comment]
Olá @renatomurasaki 
O título da página foi alterado e o menu já foi ajustado
existe um frase "Selecione abaixo o país desejado e conheça como a informação disponíveis no e-BlueInfo é organizada e atualizada."
como deve ficar essa frase?

**Comment by renatomurasaki** [comment]
Márcio, o título da primeira seção da página não precisa ser alterado. Mantenha "Sobre os conteúdos dos países". Este issue é apenas para alterar o nome do menu.

**Comment by marcioalvessilva** [comment]
Alterados!
