### ISSUE TITLE
Tradução do pop-up quando o usuário clica no ícone do Google Play ou Apple Store

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#148]
Atualmente o texto do pop-up está em inglês em todos os idiomas da interface.

![image](https://user-images.githubusercontent.com/1226218/111518051-78394380-8734-11eb-8cc9-210d9d2ca0e5.png)

**Comment by marcioalvessilva** [comment]
@renatomurasaki  - Tradução inserida, por favor validar!

**Comment by renatomurasaki** [comment]
@marcioalvessilva ajustar o texto em espanhol para manter os verbos na 3a pessoa (usted):

**DE:** O si lo prefieres haz clic aquí para acceder a la tienda Google Play.

**PARA:** O si lo prefiere, haga clic aquí para acceder a la tienda de Google Play

Em português:

**DE:** Digitalize o código QR com o celular
**PARA:** Escaneie o código QR com o celular

**Comment by marcioalvessilva** [comment]
Textos atualizado
