### ISSUE TITLE
Alterar o texto explicativo sobre Guias OPAS/OMS nos 3 idiomas na página https://e-blueinfo.teste.bvsalud.org/novidades/

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#149]
https://e-blueinfo.teste.bvsalud.org/novidades/

@marcioalvessilva manter o mesmo estilo de redação que fizemos para os demais textos que explicam as novidades:

### Português
**DE**: Na nova versão do e-BlueInfo você pode acessar coleções de guias publicadas pela OPAS/OMS relacionadas a diferentes temas prioritários como saúde sexual e reprodutiva, doenças transmissíveis e não transmissíveis, mortalidade materna e infantil, entre outros.

**PARA:** Acesse coleções de guias publicadas pela OPAS/OMS relacionadas a diferentes temas prioritários como saúde sexual e reprodutiva, doenças transmissíveis e não transmissíveis, mortalidade materna e infantil, entre outros.

### Inglês
**DE**: In the new version of e-BlueInfo you can access collections of guidelines published by PAHO/WHO related to different priority themes such as sexual and reproductive health, communicable and non-communicable diseases, maternal and child mortality, among others.

**PARA**: Access collections of guidelines published by PAHO/WHO related to different priority themes such as sexual and reproductive health, communicable and non-communicable diseases, maternal and child mortality, among others.

### Espanhol
**DE:** En la nueva versión de e-BlueInfo se puede acceder a colecciones de guías publicadas por la OPS/OMS relacionadas con diferentes temas prioritarios como salud sexual y reproductiva, enfermedades transmisibles y no transmisibles, mortalidad materna e infantil, entre otros.
**PARA:** Acceda a colecciones de guías publicadas por la OPS/OMS relacionadas con diferentes temas prioritarios como salud sexual y reproductiva, enfermedades transmisibles y no transmisibles, mortalidad materna e infantil, entre otros.

**Comment by marcioalvessilva** [comment]
Atualizados
