### ISSUE TITLE
Colocar texto e botões das lojas do Google e da Apple em outras páginas do site e-BlueInfo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#150]
Colocar o texto e as imagens das lojas para download do App

![image](https://user-images.githubusercontent.com/1226218/111519154-90f62900-8735-11eb-88f2-ebbe5e811b3b.png)

No final das seguintes páginas, nos 3 idiomas:

- https://e-blueinfo.teste.bvsalud.org/novidades/ 
- https://e-blueinfo.teste.bvsalud.org/informacoes-dos-paises/
- https://e-blueinfo.teste.bvsalud.org/dados-dos-paises-participantes/
- https://e-blueinfo.teste.bvsalud.org/
- Nas páginas dos paises (Brasil, El Salvador, Guatemala e Peru)
- Na página da OPAS/OMS

**Comment by marcioalvessilva** [comment]
@renatomurasaki
Inserido no footer 
![image](https://user-images.githubusercontent.com/48724136/111625890-23490c00-87cc-11eb-8ef1-da0d163e2ff4.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva excelente decisão!

**Comment by renatomurasaki** [comment]
@marcioalvessilva precisa verificar com o Wilson para que essa barra não apareça no celular, uma vez que esta, e outras páginas, também aparecem dentro do App.
