### ISSUE TITLE
Alterar texto que aparece depois do usuário escolher "Outro país"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#151]
### Portugues

**DE**: Não existem comunidades disponíveis, pois o seu país ainda não aderiu ao e-BlueInfo. Mas você ainda tem acesso aos documentos na seção Outras Evidências.
**PARA**: Não existem coleções de documentos disponíveis, pois o seu país ainda não aderiu ao e-BlueInfo. Mas você ainda tem acesso aos documentos na seção Outros Conteúdos.

### Espanhol

**DE**: No hay comunidades disponibles porque su país no se ha unido a e-BlueInfo. Pero aún tiene acceso a los documentos en la sección Otras Evidencias.
**PARA**: No hay colecciones de documentos disponibles, porque su país aún no se ha unido a e-BlueInfo. Pero aún tiene acceso a los documentos en la sección Otros Contenidos.

### Inglês

**DE**: There are no communities available as your country has not joined e-BlueInfo. But you still have access to the documents in the Other Evidence section.
**PARA**: There are no document collections available as your country has not joined yet to e-BlueInfo. But you still have access to the documents in the Other Contents section.

**Comment by wilsonmoura** [comment]
Realizado em 6b7a842f4a76e1e67d5d3059370096a7c920ae3e
