### ISSUE TITLE
O dado de Actualización está aparecendo sempre com a data 01/01/2020

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#152]

**Comment by wilsonmoura** [comment]
Essa data foi cravada no código para testes de layout. Existe um issue pendente relacionado a esse dado (#37). Vamos remover esse texto e deixar o código pronto para quando essa informação estiver disponível.

**Comment by wilsonmoura** [comment]
@renatomurasaki ajustes realizados.

**Comment by renatomurasaki** [comment]
@wilsonmoura para evitar confusão, melhor deixarmos somente o sticker de "Novo"/"New"/"Nuevo" utilizando a data de atualização do registro no FI-Admin. Vamos ocultar o dado de "Data de atualização", aguardando a resolução do issue #37.
