### ISSUE TITLE
A subseção do comboBox de escolha de países referente às Guias da OPAS/OMS não está traduzida

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#153]
Está mostrando sempre em inglês

![image](https://user-images.githubusercontent.com/1226218/111779395-d7ae6500-8894-11eb-8291-f8a2fb989480.png)

Acontece o mesmo para o idioma português

**Comment by wilsonmoura** [comment]
Realizado em 6b7a842f4a76e1e67d5d3059370096a7c920ae3e
