### ISSUE TITLE
Disponibilizar versão .jpg e .ai do template de divulgação que os países poderão utilizar

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#154]
Márcio, por favor, com base no template

![image](https://user-images.githubusercontent.com/1226218/111783119-a20b7b00-8898-11eb-9c33-4cc80dcbf56e.png)

Preparar versão .jpg e .ai, incluindo os logos institucionais de cada país. No caso da Guatemala que ainda não enviou as imagens, deixar em branco. No caso do Brasil, usar o template em português.

Vou apresentar e disponibilizar estas peças na segunda-feira.

**Comment by marcioalvessilva** [comment]
@renatomurasaki 

Versão Brasil

![templateBrasil](https://user-images.githubusercontent.com/48724136/111795759-3f20e080-88a6-11eb-88fa-6a0d0cc4fc68.jpg)

Versão El Salvador

![templateElSalvador](https://user-images.githubusercontent.com/48724136/111795814-4ba53900-88a6-11eb-93c2-6972ae28936d.jpg)

Versão Guatemala

![templateGuatemala](https://user-images.githubusercontent.com/48724136/111795853-58299180-88a6-11eb-884c-797a51326b52.jpg)

Versão Peru

![templatePeru](https://user-images.githubusercontent.com/48724136/111795881-624b9000-88a6-11eb-91f9-ac8ab8c5b569.jpg)

Vou alinha  a versão em Illustrator (ai) e envio por email

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. No aguardo do formato ai

**Comment by marcioalvessilva** [comment]
@renatomurasaki Segue versão Illustrator em pasta zipada em curva e normal

[TemplateAI.zip](https://github.com/bireme/e-blueinfo-wp-plugin/files/6172907/TemplateAI.zip)

**Comment by marcioalvessilva** [comment]
Documentos em Illustrator verões Twitter e Facebook
[TemplateAI.zip](https://github.com/bireme/e-blueinfo-wp-plugin/files/6174327/TemplateAI.zip)

**Comment by marcioalvessilva** [comment]
Enviados

**Comment by renatomurasaki** [comment]
@marcioalvessilva por favor, gerar novamente o .ai por conta das alterações realizadas no template para Facebook.

**Comment by marcioalvessilva** [comment]
Versões em Illustrator atualizado

[TemplateAI.zip](https://github.com/bireme/e-blueinfo-wp-plugin/files/6182386/TemplateAI.zip)
