### ISSUE TITLE
Os thumbnails não estão sendo exibidos no Google Chrome

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/e-blueinfo-wp-plugin#155]
Para resolver, será necessário implementar o protocolo HTTPS no serviço de thumbnails.

**Comment by heitorbarbieri** [comment]
Aberta solicitação para implementação do https no ITI. Aguardando resposta.

**Comment by heitorbarbieri** [comment]
Https implementado (chamada de exemplo: https://thumbs2.bireme.org/biblio-1053233/biblio-1053233.jpg). Validação feita pelo @wilsonmoura
