### ISSUE TITLE
Atualizar as imagens que aparecem na página https://e-blueinfo.teste.bvsalud.org/novidades/

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#161]
@marcioalvessilva  As imagens devem mostrar a correta funcionalidade. Sincronizar este trabalho com o @wilsonmoura . Já solicitei priorização nos ajustes de textos e traduções para que você possa capturar as telas corretas.

**Comment by marcioalvessilva** [comment]
Imagens inseridas
