### ISSUE TITLE
Enquanto não chega o texto final da página OPAS/OMS, colocar o texto explicativo desta coleção de documentos que está na página de novidades

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#167]
**Espanhol**
Acceda a colecciones de guías publicadas por la OPS/OMS relacionadas con diferentes temas prioritarios como salud sexual y reproductiva, enfermedades transmisibles y no transmisibles, mortalidad materna e infantil, entre otros.

**Português**
Acesse coleções de guias publicadas pela OPAS/OMS relacionadas a diferentes temas prioritários como saúde sexual e reprodutiva, doenças transmissíveis e não transmissíveis, mortalidade materna e infantil, entre outros.

**Inglês**
Access collections of guidelines published by PAHO/WHO related to different priority themes such as sexual and reproductive health, communicable and non-communicable diseases, maternal and child mortality, among others.

**Comment by marcioalvessilva** [comment]
@renatomurasaki o conteúdo cadastrado!
