### ISSUE TITLE
Atualizar informação nas lojas da Apple e do Google

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#170]
O texto lista países e precisa atualizar. As imagens são da versão antiga também.

**Comment by wilsonmoura** [comment]
@renatomurasaki as informações da loja do Google foram atualizadas. Na loja da Apple ainda está pendente, pois é necessário enviar a compilação da nova versão.

**Comment by wilsonmoura** [comment]
Lojas atualizadas com apoio da equipe [GoNative](https://gonative.io/).
