### ISSUE TITLE
Lentidão na navegação do App quando o usuário está logado via LDAP

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#174]
usuario logado via Facebook ou BIREME Accounts está com performance melhor. Quando não está logado a performance é melhor ainda.

**Comment by renatomurasaki** [comment]
Identificada a origem da lentidão: no sábado ocorreu uma sobrecarga ainda desconhecida no servidor da API do FI-Admin, que iniciou-se à 1h e terminou às 16h. Eliminando esta situação pontual, identificamos que o gargalo está ocorrendo no webservice dos documentos similares, por conta da alta demanda de requisição vindo da pesquisa do portal regional da BVS. @wilsonmoura está alterando a chamada de similares na tela de descrição bibliográfica do documento no e-BlueInfo para que seja assíncrona ao carregamento da página de descrição do documento. Avaliando com @heitorbarbieri alternativas para melhorar a performance do serviço similardocs, sem interferir no comportamento do resultado deste serviço dentro das páginas do iAHx, e plug-ins WP.

**Comment by wilsonmoura** [comment]
#176

**Comment by renatomurasaki** [comment]
Encerrando este issue e criando outro em similardoc.

**Comment by renatomurasaki** [comment]
https://github.com/bireme/SimilarDocs/issues/54
