### ISSUE TITLE
Material de Divulgação: Documentos similares disponíveis na Biblioteca Virtual em Saúde

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#180]
### Título
**Português**
Documentos similares disponíveis na Biblioteca Virtual em Saúde

**Espanhol:**
Documentos similares disponibles en la Biblioteca Virtual en Salud

**Inglês:**
Similar documents available in the Virtual Health Library

### Texto principal
**Português**
Na nova versão do e-BlueInfo você pode acessar informação técnica e científica, disponível nas fontes de informação da Biblioteca Virtual em Saúde, que é similar aos documentos publicados no aplicativo.

**Espanhol:**
En la nueva versión de e-BlueInfo se puede acceder a información técnica y científica, disponible en las fuentes de información de la Biblioteca Virtual en Salud, que es similar a los documentos publicados en el aplicativo.

**Inglês**
In the new version of e-BlueInfo you can access technical and scientific information, available in the information sources of the Virtual Health Library, which is similar to the documents published in the App.

**Comment by renatomurasaki** [comment]
@marcioalvessilva na página de novidades do site de divulgação, colocar o texto:

Acesse informação técnica e científica ...
Acceda a información técnica y científica ...
Access technical and scientific information ...

**Comment by marcioalvessilva** [comment]
@renatomurasaki  post enviado e conteúdo cadastrado

https://e-blueinfo.bvsalud.org/novas-funcionalidades-do-e-blueinfo/
https://e-blueinfo.bvsalud.org/es/nuevas-funcionalidades-de-e-blueinfo/
https://e-blueinfo.bvsalud.org/en/e-blueinfo-new-features/

**Comment by renatomurasaki** [comment]
Obrigado!
