### ISSUE TITLE
Página com informação do lançamento da nova versão do e-BlueInfo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#182]
@marcioalvessilva por favor, proponha uma página para ser publicada no site do e-blueInfo, em que possamos publicar:

1) Agenda do Evento
2) As apresentações
3) A gravação do evento
4) O vídeo de abertura do Dr. Jarbas

Esta página deve estar destacada na página inicial (vamos deixar uns 2 meses em destaque), como também poder ser acessada pela página de novidades.

**Comment by renatomurasaki** [comment]
https://e-blueinfo.bvsalud.org/es/perdio-el-lanzamiento-de-e-blueinfo-2-0-asista-a-la-grabacion/

Aguardando destaque na homepage.

**Comment by marcioalvessilva** [comment]
Publicado na produção!
