### ISSUE TITLE
Atualizar total de download dos documentos, baseando-se no dado dos logs antes do lançamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#185]
@wilsonmoura segue arquivo csv contendo o total de eventos de download, por ID, ocorrido prévio ao lançamento. Favor somar este total com o total registrado na base de dados.
[docID-download-total.zip](https://github.com/bireme/e-blueinfo-wp-plugin/files/6313523/docID-download-total.zip)

**Comment by wilsonmoura** [comment]
@renatomurasaki carga realizada no ambiente de produção.
Segue arquivo convertido com os dados de downloads: [downloads.txt](https://github.com/bireme/e-blueinfo-wp-plugin/files/6385985/downloads.txt)

**Comment by renatomurasaki** [comment]
@wilsonmoura muito bom!
