### ISSUE TITLE
Mudança na informação do Comitê Consultivo na página do Perú

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#187]
**Páginas**:
- https://e-blueinfo.bvsalud.org/es/datos-de-peru/
- https://e-blueinfo.bvsalud.org/en/data-from-peru/
- https://e-blueinfo.bvsalud.org/dados-do-peru/

**Alteração**:
**DE**:
Comité Consultivo Perú
Miguel Ángel Gutiérrez Reyes, Director General Tecnologías de la Información, Minsa
Albertico Quispe Cruzatti, Director Ejecutivo de Gestión de la Información, Minsa
Fernando Carbone Campoverde, Asesor del Despacho Ministerial, Minsa
Miguel Dávila, Consultor Nacional en Sistemas y Servicios de Salud, OPS Perú

**PARA**:
Comité Consultivo Perú
Ing. Jaime Alejandro Honores Coronado, Director General Tecnologías de la Información, Minsa
Ing. José Luis Segovia Juárez, Director Ejecutivo de Gestión de la Información, Minsa
Dr. Fernando Carbone Campoverde, Asesor del Despacho Ministerial, Minsa
Dr. Miguel Dávila, Consultor Nacional en Sistemas y Servicios de Salud, OPS Perú

**Comment by marcioalvessilva** [comment]
Conteúdo atualizado nos três idiomas!

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado
