### ISSUE TITLE
Legislação não recuperada no aplicativo

### ISSUE THREAD

**Issue by suelisuga** [bireme/e-blueinfo-wp-plugin#188]
Registros de legislação com status Publicado não aparecem no aplicativo.

https://fi-admin.bvsalud.org/legislation/edit/39570
Estrategia nacional de control de la epidemia de SARS COV- 2 y bases para la desescalada de las medidas de reapertura condicionada del confinamiento

![image](https://user-images.githubusercontent.com/13105683/119666593-e3c22000-be0b-11eb-896b-b937857f59d5.png)

Outros ids para teste:
ID 39571 (publicado) - Ejecución compra medicamentos Kit COVID-19 PROAM
ID 39572 (publicado)- 188-2020 - Pago de bono de riesgo COVID-19

![image](https://user-images.githubusercontent.com/13105683/119670027-ed995280-be0e-11eb-9d7a-14d7c14b655b.png)

Muito obrigada!

**Comment by renatomurasaki** [comment]
@wilsonmoura e @heitorbarbieri se refere a Guatemala. Testei via App e de fato não recupera este documento.

Me chama a atenção que no FI-Admin já foi alterado o nome da coleção:

![image](https://user-images.githubusercontent.com/1226218/119717867-3e27a480-be3d-11eb-97a7-748c617a5fa1.png)

Mas continua mostrando o nome anterior "Marco Legal y Jurídico en salud (ML)" no App e no filtro do FI-Admin.

@viniciusandrade seria o caso de atualizar o cache?

**Comment by wilsonmoura** [comment]
@renatomurasaki A coleção "Marco Legal y Jurídico en salud (ML)" está na comunidade APS (veja imagem). Já a coleção  "Marco Legal y Jurídico da COVID-19 (MLC)", exibida no print, está na comunidade COVID-19. Mas provavelmente não está exibindo essa coleção porque não está encontrando nenhum documento marcado nela. Creio que esse problema também esteja relacionado com o issue #189 (@heitorbarbieri e @viniciusandrade já estão verificando isso).

![screenshot-sites teste bvsalud org-2021 05 27-12_37_23](https://user-images.githubusercontent.com/3779520/119855534-5ef90400-bee8-11eb-85f4-6fe8cdc999d8.png)

**Comment by wilsonmoura** [comment]
@suelisuga acho que o @heitorbarbieri já resolveu esse problema em #189. Favor validar.
