### ISSUE TITLE
Registro bibliográfico não recuperado no aplicativo

### ISSUE THREAD

**Issue by suelisuga** [bireme/e-blueinfo-wp-plugin#189]
Registro bibliográfico ID 1224165 não aparece no aplicativo.
Código de salud: decreto No. 90-97 [actualizado]

Conferi e o status já está como publicado. Não consigo ver a data de quando foi marcado para e-blueinfo.
Coleção e-BlueInfo / Atención Primaria de Salud (Guatemala) / Marco Legal y Jurídico en salud (ML)

Outros registros dessa coleção aparecem... então acredito que seja algo específico nesse registro...

No FI-Admin
![image](https://user-images.githubusercontent.com/13105683/119671535-3998c700-be10-11eb-94f1-0a414fe3d4ce.png)

Histórico FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/119673418-b7110700-be11-11eb-9496-a41ed46c1fb2.png)

No aplicativo:
![image](https://user-images.githubusercontent.com/13105683/119671746-64831b00-be10-11eb-9e1e-a6293695d373.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@heitorbarbieri, por favor poderia verificar se é o caso de reindexar esta comunidade? Aguardei um dia a mais para verificar se o documento iria ser processado automáticamente mas aparentemente não foi.

Obrigado.

**Comment by heitorbarbieri** [comment]
@viniciusandrade  não estou conseguindo recuperar o documento  ID 1224165 em http://basalto01.bireme.br:9293/solr/#/pdfs/query usando as pesquisas: id:"biblio-1224165" e id:"leisref-1224165". Ele foi realmente indexado ou estou fazendo algo errado?

**Comment by viniciusandrade** [comment]
@heitorbarbieri, não entendi muito bem sua dúvida pois quem atualiza o indice **pdfs** é seu processo então não sei te responder se ele foi ou não indexado 8-) 

Consigo verificar que o documento esta disponível na API marcado corretamente na coleção ID 26 conforme chamada:

https://fi-admin-api.bvsalud.org/api/bibliographic/?collection=26&limit=100

Abraços

**Comment by heitorbarbieri** [comment]
O sistema estava gerando um erro ao encontrar uma comunidade sem coleção. Check suprimido. O documento ID 1224165 já está presente no aplicativo.
