### ISSUE TITLE
Pesquisa com excesso de resultados

### ISSUE THREAD

**Issue by suelisuga** [bireme/e-blueinfo-wp-plugin#190]
Ao realizar pesquisas no aplicativo tive dificuldade em encontrar os documentos pois a maioria das pesquisas dava resultado com mais de 100 registros.

Imagino que o uso no aplicativo fique ainda mais complicado pq gera a necessidade clicar várias vezes o "Mostrar mais"

Seria possível colocar o operador como AND e não OR? Ou colocar peso 2 nas palavras do título? 

Não sei se é assim que se processa essa pesquisa, mas ao pesquisar o título inteiro, não obtive resultados porque mantive o ":"
![image](https://user-images.githubusercontent.com/13105683/119675605-93e75700-be13-11eb-9c3a-f4b35a9839af.png)

Ao retirar, apareceu o resultado:
![image](https://user-images.githubusercontent.com/13105683/119675852-c4c78c00-be13-11eb-9889-76ca76311aaa.png)

Porém, ao pesquisar Código 90-97, eu esperava encontrar o primeiro documento como sendo o documento com (50 p.), porém ele foi o quarto item a aparecer.

![image](https://user-images.githubusercontent.com/13105683/119674697-cb093880-be12-11eb-8542-a7ac9e7ecce5.png)

O documento registrado foi a atualização desse código 90-97, mas ele não está aparecendo ainda.

Muito obrigada!

**Comment by viniciusandrade** [comment]
@wilsonmoura conforme verificamos favor aplicar regex para limpar na query os seguintes caracteres ```(. - ] [ )``` e tambem aumentar o peso da busca por título.

**Comment by wilsonmoura** [comment]
@viniciusandrade ajustes realizados conforme solicitado. Segue abaixo a linha de código atualizada com a distribuição de pesos nos termos de pesquisa:

`$query = '(ti:(QUERY)^50 OR mh:(QUERY)^30 OR ab:(QUERY)^10 OR _text_:(QUERY))';`

**Comment by wilsonmoura** [comment]
@suelisuga realizamos alguns ajustes. Favor validar.

**Comment by wilsonmoura** [comment]
@suelisuga realizamos alguns ajustes. Favor validar.

Com relação ao total de documentos, isso ocorre porque o e-BlueInfo faz a busca também no texto completo. Sendo assim, o número de documentos quase sempre será alto.
