### ISSUE TITLE
Reindexar conteúdos do e-blueinfo El Salvador devido a reorganização de coleções

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/e-blueinfo-wp-plugin#193]
@heitorbarbieri favor reindexar o índice de busca do e-blueinfo para refletir alterações aplicadas na organização da estrutura de coleções finalizadas pela @suelisuga.

Informar assim que realizado para que a @suelisuga possa validar.

**Comment by heitorbarbieri** [comment]
@viniciusandrade reindexação realizada. Favor verificar o resultado. Obrigado.

**Comment by viniciusandrade** [comment]
Obrigado @heitorbarbieri.

@suelisuga, quando possível, favor verificar se esta OK no app.
