### ISSUE TITLE
Vejo a Colombia no e-BlueInfo mas não mostra Comunidade e Coleções, mesmo os documentos estando indexados e publicados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#196]
A comunidade se chama "Vigilancia y Análisis del Riesgo en Salud Pública (Colombia)" e a mesma tem 2 coleções.

**Comment by wilsonmoura** [comment]
@heitorbarbieri favor checar se o índice Solr usado no e-BlueInfo está atualizado, pois a chamada que retorna os clusters com o total de documentos nas comunidades indica que a comunidade marcada no país Colômbia está zerada.

Chamada dos clusters usada no app e-BlueInfo:
http://basalto01.bireme.br:9293/solr/pdfs/query?q=*:*&facet=true&facet.field=com&rows=0

Comunidade: Vigilancia y Análisis del Riesgo en Salud Pública

**Comment by renatomurasaki** [comment]
@heitorbarbieri favor verificar

**Comment by heitorbarbieri** [comment]
@renatomurasaki  verifiquei que todas, ou pelo menos a maioria das urls cadastradas no FI-Admin referentes à Colômbia, têm como prefixo https://www.ins.gov.co/ que no momento que escrevo se checo com o curl, apresenta como mensagem de erro: Network is unreachable

curl -I https://www.ins.gov.co
curl: (7) Failed to connect to 2801:12:100::2:4959:760a: Network is unreachable

**Comment by renatomurasaki** [comment]
@heitorbarbieri e-mail enviado à contra-parte na Colombia reportando o problema. 

Entretanto, minha sugestão é que o processamento ignore este erro e considere apenas os metadados do Fi-Admin no processo de construção do índice. O thumbnail ficaria com a imagem padrão em todos os documentos. Obviamente o uso do e-BlueInfo fica prejudicado pelo fato do usuário não ter acesso ao texto completo, mas o App fica funcional esperando a URL voltar a funcionar. No reprocessamento e volta do funcionamento da URL, os thumbnails e indexação texto completo seriam gerados.

@wilsonmoura podemos criar uma flag para dizer se um país deve ser mostrado ou não no e-BlueInfo? Por exemplo, nesse caso, poderíamos assumir que mesmo com documentos ingressados no e-BLueInfo, o país Colombia não estaria disponível por não possibilitar o acesso aos textos completos.

**Comment by wilsonmoura** [comment]
@renatomurasaki ajustes realizados. O recurso para configurar a lista de países está disponível na área administrativa:

![screenshot-sites teste bvsalud org-2021 08 19-16_21_52](https://user-images.githubusercontent.com/3779520/130131500-2a7a539f-db62-4c26-bda3-c23227e3845b.png)

**Comment by wilsonmoura** [comment]
@renatomurasaki ajustes realizados. O recurso para configurar a lista de países está disponível na área administrativa:

![screenshot-sites teste bvsalud org-2021 08 19-16_24_51](https://user-images.githubusercontent.com/3779520/130131817-03b548d7-c156-43c7-8d05-9afcf2c63dcf.png)

**Comment by renatomurasaki** [comment]
@wilsonmoura obrigado. Com isso já podemos facilmente tomar a decisão por configuração.
@heitorbarbieri percebemos que os documentos já entraram no índice após intervenção da equipe do INS da Colombia em liberar acesso extrangeiro ao servidor deles. Obrigado.

Encerrando issue
