### ISSUE TITLE
Criar página de país para a Colombia no site de divulgação do e-BlueInfo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#197]
Márcio, segue arquivo Word para criação da página de país para a Colombia, que recentemente ingressou seus conteúdos no e-BlueInfo.

[eblueinfo.docx](https://github.com/bireme/e-blueinfo-wp-plugin/files/7008210/eblueinfo.docx)

Após criá-la, por favor, verificar com o @wilsonmoura se a mesma estará disponível também no App, menu País (Colombia) > Conozca más

**Comment by marcioalvessilva** [comment]
@renatomurasaki as páginas para Colômbia já estão criadas como rascunho nos três idiomas, posso publicar ou devo esperar mais informações?

- Tem alguma imagem de parceiros?
- Caso seja confirmado a publicação vou remover como país interessado?
- Assim que publicar passa a url para o @wilsonmoura

**Comment by renatomurasaki** [comment]
@marcioalvessilva pode publicar. Ainda não me enviaram os logos das instituições nacionais. Pode remover do país interessado e incluir em 
![image](https://user-images.githubusercontent.com/1226218/129952767-e24a7ed8-b5eb-45ad-88aa-a533b883d30a.png)

**Comment by marcioalvessilva** [comment]
@wilsonmoura,  segue link

https://e-blueinfo.bvsalud.org/es/datos-decolombia/
https://e-blueinfo.bvsalud.org/en/data-from-colombia/
https://e-blueinfo.bvsalud.org/dados-de-colombia/

**Comment by wilsonmoura** [comment]
@renatomurasaki páginas do país Colômbia inseridas no menu do app conforme solicitado.

**Comment by renatomurasaki** [comment]
@wilsonmoura obrigado. Validado
