### ISSUE TITLE
Criar banner para a comunidade Atenção Primária em Saúde do Paraguay

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#199]
Imagem requerida e logos institucionais estão disponíveis em

https://drive.google.com/drive/folders/1_MMGC_hRD-lSD2jfGvnxOClDTQumzQ9z

**Comment by marcioalvessilva** [comment]
@renatomurasaki, segue link da imagem

https://github.com/bireme/artes-graficas/blob/main/eblueinfo/banner-app/jpg/banner-comunidade-paraguai-1.jpg

**Comment by renatomurasaki** [comment]
@suelisuga segue o banner para ser incluído na Comunidade APS do Paraguai

**Comment by marcioalvessilva** [comment]
Finalizado!
