### ISSUE TITLE
Criar a página de país no e-BlueInfo (App e site) para o Paraguay

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#200]
Segue formulário preenchido pelo Comitê Local de Conteúdos do Paraguay

[Formulario con información sobre el país en eBlueInfo.docx](https://github.com/bireme/e-blueinfo-wp-plugin/files/7079749/Formulario.con.informacion.sobre.el.pais.en.eBlueInfo.docx)

**Comment by marcioalvessilva** [comment]
@renatomurasaki @wilsonmoura 
Segue links da páginas do Paraguai

ES - https://e-blueinfo.bvsalud.org/es/datos-de-paraguay/
PT - https://e-blueinfo.bvsalud.org/dados-do-paraguai/
EN - https://e-blueinfo.bvsalud.org/en/data-from-paraguay/

Posso liberar por completo no site?
- Inserir o nome do Paraguai no titulo do site
- Remover o Paraguai da lista de interesse
- Inserir na página dos conteúdo dos países

Fico no aguardo!

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado. Por favor, padronize o nome do App neste texto para e-BlueInfo. 

Favor aguardar que os conteúdos do Paraguay estejam corretos para executar as ações que você listou.

**Comment by wilsonmoura** [comment]
@renatomurasaki páginas do país Paraguai inseridas no menu do app conforme solicitado.

**Comment by marcioalvessilva** [comment]
Página publicada!
