### ISSUE TITLE
Analisar a implementação o código GA-4 na instancia sites.bvsalud.org/e-blueinfo App

### ISSUE THREAD

**Issue by marcoslmori** [bireme/e-blueinfo-wp-plugin#203]
Analisar a implementação o código GA-4 na instância sites.bvsalud.org/e-blueinfo App

Código cadastrado em: https://paho.sharepoint.com/:x:/s/BIR/EVzX0jtquElLhFx_jU--UdQBQg1kS3eDzXC7QhMIN5Bq4g?email=morimarc%40paho.org&e=4%3Atv0Swq&at=9&CID=5487f9bd-3996-c1fa-529b-56b54b77a3a5

**Comment by wilsonmoura** [comment]
@marcoslmori fizemos ajustes para que ambos os códigos possam ser usados. Nas configurações do plugin, basta colocar os códigos em linhas separadas. Favor atualizar o plugin e validar.
