### ISSUE TITLE
Os "botões" para acessar os cadernos, livros e etc. não funcionam

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#22]
Os "botões" para acessar os cadernos, livros e etc. não funcionam. Acredito que esteja com algum erro. Meu aparelho é Samsung Galaxy note 9. Pode ser alguma incompatibilidade com o aparelho?

https://play.google.com/store/apps/details?id=org.bvsalud.eblueinfo&hl=pt_BR&reviewId=gp%3AAOqpTOFwp9td63A_7OvbZUCqhKcKwwD8BOe0dLXMGi7ycgf6RSCAsYuEMqYjN1PnEOrGtR6GbC3sbuDEErKTFag

**Comment by wilsonmoura** [comment]
Atualizamos o comentário feito pela usuária na Google Store. Encerraremos a issue, mas vamos continuar monitorando o feedback.
