### ISSUE TITLE
Link da "Política Geral de Provacidade da OPAS" apresenta problema

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/e-blueinfo-wp-plugin#25]
O link da "Política Geral de Provacidade da OPAS" na página "POLÍTICA DE PRIVACIDADE DOS SITES E SISTEMAS WEB DA BIREME/OPAS"  quando clicado apresenta a mesnagem de invalid SSL certificate.

**Comment by wilsonmoura** [comment]
Testamos o link em um site que checa certificados (SSL Checker), e o mesmo acusou que a implementação do certificado não está completa nesse site.

Link com erro (invalid ssl certificate): https://www.paho.org/hq/index.php?option=com_content&view=article&id=3201:paho-website-privacy-policy&Itemid=2410&lang=es
Link de verificação do certificado: https://www.sslshopper.com/ssl-checker.html#hostname=www.paho.org

Já informamos ao ITI por email para que possam verificar com a equipe de infraestrutura da PAHO, que são os responsáveis pelo site www.paho.org
