### ISSUE TITLE
Cambiar orden de relevancia en la recuperación de los documentos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#29]
Relevancia propuesta en orden decreciente:
título, decs/mesh, resumen y texto completo

**Comment by heitorbarbieri** [comment]
A solução é colocar "boosting" nos termos da expressão de busca.
Segue a sugestão de expressão de busca no Solr:

ti:"dengue"^4 OR ti_en:"dengue"^4 OR ti_es:"dengue"^4 OR ti_pt:"dengue"^4 OR ab:"dengue"^2 OR ab_en:"dengue"^2  OR ab_es:"dengue"^2 OR OR ab_pt:"dengue"^2 OR _text_:"dengue" 

Ainda não podemos pesquisar pelo descritor pois somente os códigos é que estão indexados.

**Comment by wilsonmoura** [comment]
Para que a relevância aceite mais que um termo de pesquisa, ajustamos a expressão da seguinte forma:

Somente um termo: `((ti:dengue^4) OR (ab:dengue^2) OR (_text_:dengue))`
Múltiplos termos: `((ti:dengue AND amamentação^4) OR (ab:dengue AND amamentação^2) OR (_text_:dengue AND amamentação))`

Favor realizar testes em http://sites.teste.bvsalud.org/e-blueinfo/app?country=30
