### ISSUE TITLE
Destacar informações dos documentos

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/e-blueinfo-wp-plugin#37]
Exibir na lista de documentos:

- Tipo de mídia
- Data da última atualização
- Total de downloads

**Comment by wilsonmoura** [comment]
Relacionado com:
- Tipo de mídia: bireme/XDocumentServer#32
- Data da última atualização: bireme/fi-admin#1098

**Comment by wilsonmoura** [comment]
Tarefa pendente: data da última atualização bireme/fi-admin#1104

**Comment by renatomurasaki** [comment]
@wilsonmoura favor revisar, porque o sticker "Novo"/"Nuevo"/"New" que aparece no thumbnail parece estar baseada na data de atualização do registro bibliográfico. Veja exemplo abaixo

![image](https://user-images.githubusercontent.com/1226218/112000572-e008d900-8afc-11eb-86b7-52390e2d1e8c.png)

Histórico no registro do Fi-Admin para o documento "El cigarrillo electrónico: un problema de salud pública emergente"

![image](https://user-images.githubusercontent.com/1226218/112000742-062e7900-8afd-11eb-9901-056cfa75d5db.png)

**Comment by renatomurasaki** [comment]
@wilsonmoura para manter coerencia com o comportamento do sticker, melhor nesse primeiro momento utilizar a mesma data para mostrar quando foi atualizado.
