### ISSUE TITLE
Alterar a expressão de busca do e-BlueInfo

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/e-blueinfo-wp-plugin#47]
Mudar de:

 $query = '((ti:QUERY)^4 OR (ab:QUERY)^2 OR (_text_:QUERY))';

para 

$query = '((mh:QUERY)^50 OR (ti:QUERY)^30 OR (ab:QUERY)^10 OR (_text_:QUERY))';

**Comment by renatomurasaki** [comment]
Favor corrigir a expressão de busca:

$query = '(mh:(QUERY)^50 OR ti:(QUERY)^30 OR ab:(QUERY)^10 OR text:(QUERY))';
