### ISSUE TITLE
Crear versión 2 del mockup pos reunión 20190711

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#48]
Versión 1:
![mockup-e-BlueInfo](https://user-images.githubusercontent.com/1226218/68396903-14bb0100-0151-11ea-9ab3-5cce96c75cc9.jpg)

**Comment by wilsonmoura** [comment]
Versão final do mockup disponível em http://mockups.teste.bireme.org/eblueinfoapp
