### ISSUE TITLE
Integrar áreas exclusivas com informação por pais

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/e-blueinfo-wp-plugin#78]

**Comment by renatomurasaki** [comment]
A área exclusiva por país dentro do e-blueinfo.bvsalud.org deverá estar integrada no App.

**Comment by wilsonmoura** [comment]
Aguardando links das páginas de cada país para avançar nessa atividade.

**Comment by marcioalvessilva** [comment]
Páginas criadas na produção (aguardando conteúdo)

Link disponível:

**Link Brasil**
https://e-blueinfo.bvsalud.org/dados-do-brasil/
https://e-blueinfo.bvsalud.org/es/datos-de-brasil/
https://e-blueinfo.bvsalud.org/en/data-from-brazil/

**Link El Salvador**
https://e-blueinfo.bvsalud.org/dados-de-el-salvador/
https://e-blueinfo.bvsalud.org/es/datos-de-el-salvador/
https://e-blueinfo.bvsalud.org/en/data-from-el-salvador/


**Link Guatemala**
https://e-blueinfo.bvsalud.org/dados-da-guatemala/
https://e-blueinfo.bvsalud.org/es/datos-de-guatemala/
https://e-blueinfo.bvsalud.org/en/data-from-guatemala/


**Link Peru**
https://e-blueinfo.bvsalud.org/dados-do-peru/
https://e-blueinfo.bvsalud.org/es/datos-de-peru/
https://e-blueinfo.bvsalud.org/en/data-from-peru/
