### ISSUE TITLE
Deixar mais claro o tipo de conteúdo existente por país

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#82]
Há alguns feedbacks de usuarios achando que haveria informaçao de todas as áreas da saúde. Outro item importante é que 50% das pessoas que entram no App não continuam navegando.

**Comment by renatomurasaki** [comment]
- Deixar explicita esta informação no site e-blueinfo.bvsalud.org
- Criar algum mecanismo na página de comunidades que convide o usuario a explorar os conteúdos disponíveis

**Comment by wilsonmoura** [comment]
Relacionado com bireme/XDocumentServer#39
