### ISSUE TITLE
Definir padrão de dimensão e formato para as imagens do banner do rodapé

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#88]
Banner referente a Comunidade
Rodapé referente as instituições que participam do e-BlueInfo

**Comment by wilsonmoura** [comment]
- Banner referente a Comunidade: documentado em [How to add community banners](https://github.com/bireme/e-blueinfo-wp-plugin/blob/2.0/doc/how-to-add-community-banners.md)
- Rodapé referente as instituições que participam do e-BlueInfo: documentado em [How to add images of institutional supporters](https://github.com/bireme/e-blueinfo-wp-plugin/blob/2.0/doc/how-to-add-images-of-institutional-supporters.md)
