### ISSUE TITLE
Revisar traduções

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#89]
### 1) Disclaimer "There are no..." precisa de tradução para o português e espanhol.

![image](https://user-images.githubusercontent.com/1226218/97017510-64dad100-1524-11eb-8ffa-4e0da251bd93.png)

### 2) Opção "Other Country" precisa de tradução para o português e espanhol.

![image](https://user-images.githubusercontent.com/1226218/97017871-d0bd3980-1524-11eb-932e-2dd2f45d0974.png)

### 3) Mensagens de pop-up com feedback das ações do usuário logado

![image](https://user-images.githubusercontent.com/1226218/97018361-71135e00-1525-11eb-91f8-66ff5c70ad18.png)

![image](https://user-images.githubusercontent.com/1226218/97018497-97d19480-1525-11eb-875c-9f95e5683402.png)

**Comment by wilsonmoura** [comment]
@renatomurasaki traduções atualizadas.
