### ISSUE TITLE
Página de redirecionamento errada após login via autenticação MinhaBVS (AD)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#90]
Login usando AD BIR do MinhaBVS
![image](https://user-images.githubusercontent.com/1226218/97018977-26461600-1526-11eb-986a-c68868ddd915.png)

No ambiente de testes, após clicar em login, o que ocorre é o fechamento da janela/aba do browser. Ao digitar a URL no browser para acessar novamente o ambiente de testes, percebe-se que a sessão está com a autenticação do usuário e senha

![image](https://user-images.githubusercontent.com/1226218/97019304-8b9a0700-1526-11eb-9273-2d0147841415.png)

Não sei se este comportamento se repetirá dentro do App.

Este mesmo comportamento ocorre para os logins de redes sociais.

**Comment by wilsonmoura** [comment]
Para manter o bom funcionamento de navegação no app, houve a necessidade de forçar o sistema a resetar o histórico de navegação após o login. Para que não ocorra esse comportamento no browser, é necessário abrir o link da página principal de forma direta (sem abrir uma nova aba vazia). Vale reforçar que esse erro não vai ocorrer no app, pois o framework que usamos para encapsular o site já resolve esse comportamento.
