### ISSUE TITLE
Criar serviço no livezilla para o serviço de ajuda no APP. 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/e-blueinfo-wp-plugin#91]
Criar grupo e-blueInfo no livezilla para disponibilizar serviço de suporte técnico no APP

**Comment by marcoslmori** [comment]
Criar grupo e-blueInfo no livezilla para disponibilizar serviço de suporte técnico no APP

**Comment by wilsonmoura** [comment]
Realizado em #103
