### ISSUE TITLE
Atualizar informações do InfoButton

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/e-blueinfo-wp-plugin#93]
Ajustes:
- Alterar título do card para Outros Conteúdos
- Alterar texto do card para "Buscar evidências científicas na Biblioteca Virtual em Saúde"
- Incluir texto do ícone modal
- Atualizar imagem do card

**Comment by wilsonmoura** [comment]
@renatomurasaki pendente texto do modal.

**Comment by wilsonmoura** [comment]
@marcioalvessilva pendente imagem atualizada do card.

**Comment by renatomurasaki** [comment]
@wilsonmoura texto do modal em 3 idiomas: ver na página https://e-blueinfo.teste.bvsalud.org/novidades/

**Comment by wilsonmoura** [comment]
Ajustes realizados.
