### ISSUE TITLE
Perú - banneres 600x300 de APS e COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#97]
Seguem os banneres 600x300 das comunidades do Peru
![600x300 COVID-19](https://user-images.githubusercontent.com/1226218/99994886-66ecb580-2d98-11eb-8bb0-7c2ff3773445.png)
![600x300 Atención Primaria](https://user-images.githubusercontent.com/1226218/99994888-694f0f80-2d98-11eb-8bc9-2e5c4f06d50e.png)

**Comment by wilsonmoura** [comment]
Imagens incluídas nas respectivas comunidades.
