### ISSUE TITLE
Perú - banner 200x100 no rodapé das páginas do App e da página do país.

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/e-blueinfo-wp-plugin#98]
Os compontes do banner foram enviados separadamente. Por favor, junta-los em um único banner de 200x100, na mesma ordem que aparece no banner 600x300

![200x100 Logo La Salud Depende de Todos](https://user-images.githubusercontent.com/1226218/99995013-97345400-2d98-11eb-8395-9ace560ca68a.png)
![200x100 Logo Minsa](https://user-images.githubusercontent.com/1226218/99995015-97ccea80-2d98-11eb-952d-3ad539ef1b00.png)
![200x100 Logo El Perú Primero](https://user-images.githubusercontent.com/1226218/99995017-98658100-2d98-11eb-9da2-65762911ffc3.png)

**Comment by wilsonmoura** [comment]
Imagens incluídas nas respectivas comunidades.

**Comment by wilsonmoura** [comment]
Imagens incluídas no respectivo país.
